# Generated by Django 4.2.13 on 2026-05-14 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placements', '0001_initial'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='placements.internshipplacement'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='criteriascore',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria'),
        ),
        migrations.AddField(
            model_name='criteriascore',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='evaluations.evaluation'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('placement', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='criteriascore',
            unique_together={('evaluation', 'criteria')},
        ),
    ]
